# Generated by Django 5.1.2 on 2025-05-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_transaccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
