# Generated by Django 5.2 on 2025-05-26 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0004_producto_codigo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
    ]
