# Generated by Django 5.1.4 on 2025-05-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpay_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=26, unique=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WebPayTransaction',
        ),
    ]
