# Generated by Django 5.1.2 on 2025-06-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('administrador', 'Administrador'), ('contador', 'Contador')], default='cliente', max_length=20),
        ),
    ]
